// Maps a product's exact `name` (as stored in Firestore) to its locally-served image,
// served from /public/product-images/. 114 entries are the original catalog's photos
// (mirrored from customer/assets/Cleaned_Products). 166 more were added from manually
// sourced photos for the newer 196-item catalog, matched by hand against actual
// packaging, background-removed and styled through the same pipeline as the original
// set. 17 products in the newer catalog have no photo — no usable source photo existed
// for them — and 2 more (White Kadala / Black Benny, Bourbon Neapolitan Cream) were
// explicitly held back; these fall through to the placeholder icon rather than showing
// an incorrect image. Filenames containing "&", "+", or "/" are sanitized (spelled out /
// dropped) — Vite's static file serving 500s on paths containing those characters.

const productImages = {
  "Local Greens (Bal Chambu)": "/product-images/Local%20Greens%20Bal%20Chambu.png",
  "Vada Paruppu (Urad Dal)": "/product-images/Vada%20Paruppu%20Urad%20Dal.png",
  "Dream Cream Orange / Cashewnut": "/product-images/Dream%20Cream%20Orange%20Cashewnut.png",
  "Ginger": "/product-images/Ginger.png",
  "Dates Syrup": "/product-images/Dates%20Syrup.png",
  "TT Asafoetida Cake": "/product-images/TT%20Asafoetida%20Cake.png",
  "Power Soap": "/product-images/Power%20Soap.png",
  "Milma Ghee": "/product-images/Milma%20Ghee.png",
  "Sunfeast Golden Bakery": "/product-images/Sunfeast%20Golden%20Bakery.png",
  "Lia Agarbathy (Apple/Rose/Lavender/Jasmine)": "/product-images/Lia%20Agarbathy%20Apple%20Rose%20Lavender%20Jasmine.png",
  "Tiger KR Coconut": "/product-images/Tiger%20KR%20Coconut.png",
  "Mango": "/product-images/Mango.png",
  "50-50 Biscuits": "/product-images/50-50%20Biscuits.png",
  "786 Surekha Rice": "/product-images/786%20Surekha%20Rice.png",
  "Anus Chilly Sauce": "/product-images/Anus%20Chilly%20Sauce.png",
  "Anus Chukku Kappi (Ginger Coffee Mix)": "/product-images/Anus%20Chukku%20Kappi%20Ginger%20Coffee%20Mix.png",
  "Anus Dates Pickle": "/product-images/Anus%20Dates%20Pickle.png",
  "Anus Lemon Pickle": "/product-images/Anus%20Lemon%20Pickle.png",
  "Anus Mango Pickle": "/product-images/Anus%20Mango%20Pickle.png",
  "Anus Soya Sauce": "/product-images/Anus%20Soya%20Sauce.png",
  "Anus Tender Mango Pickle": "/product-images/Anus%20Tender%20Mango%20Pickle.png",
  "Anus Tomatto Sauce": "/product-images/Anus%20Tomatto%20Sauce.png",
  "AVT Premium Tea": "/product-images/AVT%20Premium%20Tea.png",
  "Bakers Kasuri Methi": "/product-images/Bakers%20Kasuri%20Methi.png",
  "Banana Flower (Ullie Poo)": "/product-images/Banana%20Flower%20Ullie%20Poo.png",
  "Beans": "/product-images/Beans.png",
  "Beet Root": "/product-images/Beet%20Root.png",
  "Bharath Doppi Rice": "/product-images/Bharath%20Doppi%20Rice.png",
  "Black Pepper Powder": "/product-images/Black%20Pepper%20Powder.png",
  "Boost 200 gm Pouch": "/product-images/Boost%20200%20gm%20Pouch.png",
  "Boost 500 gm Jar": "/product-images/Boost%20500%20gm%20Jar.png",
  "Bounty (S.Bounty)": "/product-images/Bounty%20S.Bounty.png",
  "Brinjal": "/product-images/Brinjal.png",
  "Bru Coffee Instant": "/product-images/Bru%20Coffee%20Instant.png",
  "Bru Coffee Pure": "/product-images/Bru%20Coffee%20Pure.png",
  "Capsicum (Green)": "/product-images/Capsicum%20Green.png",
  "Carrot": "/product-images/Carrot.png",
  "Cashew Split": "/product-images/Cashew%20Split.png",
  "Cheru Paruppu (Moong Dal)": "/product-images/Cheru%20Paruppu%20Moong%20Dal.png",
  "Chicken Masala Powder": "/product-images/Chicken%20Masala%20Powder.png",
  "Chilli Powder": "/product-images/Chilli%20Powder.png",
  "Chocolate Horlicks Refill 1Kg": "/product-images/Chocolate%20Horlicks%20Refill%201Kg.png",
  "Chocolate Horlicks Sachet 75g": "/product-images/Chocolate%20Horlicks%20Sachet%2075g.png",
  "Clear Hair Oil 75ml": "/product-images/Clear%20Hair%20Oil%2075ml.png",
  "Clinic Plus Hair Shampoo": "/product-images/Clinic%20Plus%20Hair%20Shampoo.png",
  "Clinic Plus Hair Shampoo Straight & Shine 175ml": "/product-images/Clinic%20Plus%20Hair%20Shampoo%20Straight%20and%20Shine%20175ml.png",
  "Clinic Plus Hair Shampoo Strong & Extra Thick 175ml": "/product-images/Clinic%20Plus%20Hair%20Shampoo%20Strong%20and%20Extra%20Thick%20175ml.png",
  "Clinic Plus Hair Shampoo Strong & Shine 6ml": "/product-images/Clinic%20Plus%20Hair%20Shampoo%20Strong%20and%20Shine%206ml.png",
  "Clinic Plus Hair Shampoo Strong Scalp": "/product-images/Clinic%20Plus%20Hair%20Shampoo%20Strong%20Scalp.png",
  "Clinic Plus Strong And Smooth 6ml": "/product-images/Clinic%20Plus%20Strong%20And%20Smooth%206ml.png",
  "Close Up Toothpaste Deep Action Red Hot Gel 26g": "/product-images/Close%20Up%20Toothpaste%20Deep%20Action%20Red%20Hot%20Gel%2026g.png",
  "Close Up Toothpaste Ever Fresh Red Hot Gel 40g": "/product-images/Close%20Up%20Toothpaste%20Ever%20Fresh%20Red%20Hot%20Gel%2040g.png",
  "Comfort Fabric Conditioner Blue 220ml": "/product-images/Comfort%20Fabric%20Conditioner%20Blue%20220ml.png",
  "Comfort Fabric Conditioner Pink 220ml": "/product-images/Comfort%20Fabric%20Conditioner%20Pink%20220ml.png",
  "Coriander Leaves (Malli)": "/product-images/Coriander%20Leaves%20Malli.png",
  "Coriander Powder": "/product-images/Coriander%20Powder.png",
  "Cucumber": "/product-images/Cucumber.png",
  "Cumin (Jeera) Powder": "/product-images/Cumin%20Jeera%20Powder.png",
  "Curry Leaves (K. Leaves)": "/product-images/Curry%20Leaves%20K.%20Leaves.png",
  "Cycle 3-in-1 Agarbathi": "/product-images/Cycle%203-in-1%20Agarbathi.png",
  "Dabur Almond Hair Oil": "/product-images/Dabur%20Almond%20Hair%20Oil.png",
  "Dabur Amla Hair Oil": "/product-images/Dabur%20Amla%20Hair%20Oil.png",
  "Dabur Glucose": "/product-images/Dabur%20Glucose.png",
  "Dabur Red Toothpaste": "/product-images/Dabur%20Red%20Toothpaste.png",
  "Dabur Vatika Hair Oil": "/product-images/Dabur%20Vatika%20Hair%20Oil.png",
  "Dark Fantasy Bourbon": "/product-images/Dark%20Fantasy%20Bourbon.png",
  "Dark Fantasy Vanilla": "/product-images/Dark%20Fantasy%20Vanilla.png",
  "Devon Chilly Powder": "/product-images/Devon%20Chilly%20Powder.png",
  "Devon Coriander Powder": "/product-images/Devon%20Coriander%20Powder.png",
  "Devon Corn Starch (household/cooking use)": "/product-images/Devon%20Corn%20Starch%20household%20cooking%20use.png",
  "DH Corn Flour": "/product-images/DH%20Corn%20Flour.png",
  "DH Easy Idiyappam": "/product-images/DH%20Easy%20Idiyappam.png",
  "DH Idiyappam / Appam Podi": "/product-images/DH%20Idiyappam%20Appam%20Podi.png",
  "DH Macroni": "/product-images/DH%20Macroni.png",
  "DH Palada Payasam Mix": "/product-images/DH%20Palada%20Payasam%20Mix.png",
  "DH Roast Ragi Powder": "/product-images/DH%20Roast%20Ragi%20Powder.png",
  "DH Turmeric Powder": "/product-images/DH%20Turmeric%20Powder.png",
  "DH Vermicelli Mix": "/product-images/DH%20Vermicelli%20Mix.png",
  "DH White Puttu Podi": "/product-images/DH%20White%20Puttu%20Podi.png",
  "Dolphin IR8 Pachari Rice": "/product-images/Dolphin%20IR8%20Pachari%20Rice.png",
  "Dove Bathing Soap Cream Beauty 50g": "/product-images/Dove%20Bathing%20Soap%20Cream%20Beauty%2050g.png",
  "Dove Daily Shine Shampoo & Conditioner Twin Sachet": "/product-images/Dove%20Daily%20Shine%20Shampoo%20and%20Conditioner%20Twin%20Sachet.png",
  "Dove Glycolic Hydration Mid Shampoo 180ml": "/product-images/Dove%20Glycolic%20Hydration%20Mid%20Shampoo%20180ml.png",
  "Dove Hair Conditioner Daily Shine": "/product-images/Dove%20Hair%20Conditioner%20Daily%20Shine.png",
  "Dove Hair Conditioner Dryness Care 80ml": "/product-images/Dove%20Hair%20Conditioner%20Dryness%20Care%2080ml.png",
  "Dove Hair Conditioner Hair Fall Rescue": "/product-images/Dove%20Hair%20Conditioner%20Hair%20Fall%20Rescue.png",
  "Dove Hair Conditioner Intense Damage Therapy": "/product-images/Dove%20Hair%20Conditioner%20Intense%20Damage%20Therapy.png",
  "Dove Hair Shampoo & Conditioner Hair Fall Therapy": "/product-images/Dove%20Hair%20Shampoo%20and%20Conditioner%20Hair%20Fall%20Therapy.png",
  "Dove Hair Shampoo & Conditioner Intense Repair": "/product-images/Dove%20Hair%20Shampoo%20and%20Conditioner%20Intense%20Repair.png",
  "Dove Hair Shampoo Anti Dandruff Therapy": "/product-images/Dove%20Hair%20Shampoo%20Anti%20Dandruff%20Therapy.png",
  "Dove Hair Shampoo Clean & Fresh 6ml": "/product-images/Dove%20Hair%20Shampoo%20Clean%20and%20Fresh%206ml.png",
  "Dove Hair Shampoo Daily Shine": "/product-images/Dove%20Hair%20Shampoo%20Daily%20Shine.png",
  "Dove Hair Shampoo Dandruff Care 80ml": "/product-images/Dove%20Hair%20Shampoo%20Dandruff%20Care%2080ml.png",
  "Dove Hair Shampoo Dryness Care 80ml": "/product-images/Dove%20Hair%20Shampoo%20Dryness%20Care%2080ml.png",
  "Dove Hair Shampoo Hair Fall Rescue 80ml": "/product-images/Dove%20Hair%20Shampoo%20Hair%20Fall%20Rescue%2080ml.png",
  "Dove Hair Shampoo Hair Fall Therapy": "/product-images/Dove%20Hair%20Shampoo%20Hair%20Fall%20Therapy.png",
  "Dove Hair Shampoo Healthy Ritual For Growing Hair": "/product-images/Dove%20Hair%20Shampoo%20Healthy%20Ritual%20For%20Growing%20Hair.png",
  "Dove Hair Shampoo Intense Repair": "/product-images/Dove%20Hair%20Shampoo%20Intense%20Repair.png",
  "Dove Men+ Care Ad 2In1 Shampoo+Conditioner": "/product-images/Dove%20Men%20Plus%20Care%20Ad%202In1%20Shampoo%20Plus%20Conditioner.png",
  "Dove Pink Serum Beauty Bar": "/product-images/Dove%20Pink%20Serum%20Beauty%20Bar.png",
  "Drumstick (Salladu)": "/product-images/Drumstick%20Salladu.png",
  "E-fee Washing Liquid": "/product-images/E-fee%20Washing%20Liquid.png",
  "Egg Masala Powder": "/product-images/Egg%20Masala%20Powder.png",
  "Elite Atta": "/product-images/Elite%20Atta.png",
  "Elite Maida": "/product-images/Elite%20Maida.png",
  "Elite Rava": "/product-images/Elite%20Rava.png",
  "Elite Rice Puttu Podi": "/product-images/Elite%20Rice%20Puttu%20Podi.png",
  "Exo Dishwash Bar": "/product-images/Exo%20Dishwash%20Bar.png",
  "Flowers (assorted, for pooja)": "/product-images/Flowers%20assorted%2C%20for%20pooja.png",
  "Garam Masala Powder": "/product-images/Garam%20Masala%20Powder.png",
  "Ginger Garlic Paste": "/product-images/Ginger%20Garlic%20Paste.png",
  "Ginger Pickle": "/product-images/Ginger%20Pickle.png",
  "Glow & Lovely Facewash Fairness 50g": "/product-images/Glow%20and%20Lovely%20Facewash%20Fairness%2050g.png",
  "Gold Walnut": "/product-images/Gold%20Walnut.png",
  "Good Day Butter": "/product-images/Good%20Day%20Butter.png",
  "Good Day Cashew": "/product-images/Good%20Day%20Cashew.png",
  "Good Day Chocochip": "/product-images/Good%20Day%20Chocochip.png",
  "Good Day Pista Badam": "/product-images/Good%20Day%20Pista%20Badam.png",
  "Gooseberry (Nelli Kai)": "/product-images/Gooseberry%20Nelli%20Kai.png",
  "Green Chilly": "/product-images/Green%20Chilly.png",
  "Green Peas 1st": "/product-images/Green%20Peas%201st.png",
  "Hamam Soap": "/product-images/Hamam%20Soap.png",
  "Hellmann's Mayo Smoky Tandoori 85g": "/product-images/Hellmann's%20Mayo%20Smoky%20Tandoori%2085g.png",
  "Hellmann's Sauce Mayonnaise Doy Pack 85g": "/product-images/Hellmann's%20Sauce%20Mayonnaise%20Doy%20Pack%2085g.png",
  "Horlicks Plain Biscuits 45g": "/product-images/Horlicks%20Plain%20Biscuits%2045g.png",
  "Horlicks Ready-to-Drink 125ml Chocolate": "/product-images/Horlicks%20Ready-to-Drink%20125ml%20Chocolate.png",
  "Idiyappam Podi (steamed)": "/product-images/Idiyappam%20Podi%20steamed.png",
  "Indulekha Hair Shampoo Bringha Hair Fall Cleanser": "/product-images/Indulekha%20Hair%20Shampoo%20Bringha%20Hair%20Fall%20Cleanser.png",
  "Kadala Mavu (Chickpea Flour)": "/product-images/Kadala%20Mavu%20Chickpea%20Flour.png",
  "Kadala Paruppu (Chana Dal)": "/product-images/Kadala%20Paruppu%20Chana%20Dal.png",
  "Kashmiri Chilli Powder": "/product-images/Kashmiri%20Chilli%20Powder.png",
  "Kellogg's Chocos": "/product-images/Kellogg's%20Chocos.png",
  "Kellogg's Corn Flakes": "/product-images/Kellogg's%20Corn%20Flakes.png",
  "Kismiss Medium (Raisins Seedless)": "/product-images/Kismiss%20Medium%20Raisins%20Seedless.png",
  "Kissan Hari Chutney 100g Doy": "/product-images/Kissan%20Hari%20Chutney%20100g%20Doy.png",
  "Kissan Imli Khajoor Chutney 100g Doy": "/product-images/Kissan%20Imli%20Khajoor%20Chutney%20100g%20Doy.png",
  "Kissan Jam Mixed Fruit 100g": "/product-images/Kissan%20Jam%20Mixed%20Fruit%20100g.png",
  "Kissan Jam Orange Marmalade 500g": "/product-images/Kissan%20Jam%20Orange%20Marmalade%20500g.png",
  "Kissan Ketchup Fresh Tomato Chotu 90g": "/product-images/Kissan%20Ketchup%20Fresh%20Tomato%20Chotu%2090g.png",
  "Kissan Lehsun Mirch Chutney 100g Doy": "/product-images/Kissan%20Lehsun%20Mirch%20Chutney%20100g%20Doy.png",
  "Kit Kat Miniatures": "/product-images/Kit%20Kat%20Miniatures.png",
  "Kitchen King BT Rice": "/product-images/Kitchen%20King%20BT%20Rice.png",
  "Knorr Cream of Broccoli Cup-A-Soup 12.5g": "/product-images/Knorr%20Cream%20of%20Broccoli%20Cup-A-Soup%2012.5g.png",
  "Knorr Cup A Soup Instant Hot & Sour 11g": "/product-images/Knorr%20Cup%20A%20Soup%20Instant%20Hot%20and%20Sour%2011g.png",
  "Knorr Cup A Soup Instant Manchow 12g": "/product-images/Knorr%20Cup%20A%20Soup%20Instant%20Manchow%2012g.png",
  "Knorr Cup A Soup Instant Mix Vegetable 18g": "/product-images/Knorr%20Cup%20A%20Soup%20Instant%20Mix%20Vegetable%2018g.png",
  "Knorr Cup A Soup Instant Sweet Corn 10g": "/product-images/Knorr%20Cup%20A%20Soup%20Instant%20Sweet%20Corn%2010g.png",
  "Knorr Cup A Soup Instant Tomato Chatpata 16g": "/product-images/Knorr%20Cup%20A%20Soup%20Instant%20Tomato%20Chatpata%2016g.png",
  "KP Herbal Paste": "/product-images/KP%20Herbal%20Paste.png",
  "KPR Jaya Rice": "/product-images/KPR%20Jaya%20Rice.png",
  "Ladies Finger": "/product-images/Ladies%20Finger.png",
  "Lemon": "/product-images/Lemon.png",
  "Lifebuoy Bathing Soap Care 100% Stronger Germ Protection": "/product-images/Lifebuoy%20Bathing%20Soap%20Care%20100%25%20Stronger%20Germ%20Protection.png",
  "Lifebuoy Bathing Soap Lemon Fresh": "/product-images/Lifebuoy%20Bathing%20Soap%20Lemon%20Fresh.png",
  "Lifebuoy Bathing Soap Total 10 4x65g": "/product-images/Lifebuoy%20Bathing%20Soap%20Total%2010%204x65g.png",
  "Lifebuoy Bathing Soap Turmeric And Honey": "/product-images/Lifebuoy%20Bathing%20Soap%20Turmeric%20And%20Honey.png",
  "Lifebuoy Hand Wash Powder to Liquid 10g": "/product-images/Lifebuoy%20Hand%20Wash%20Powder%20to%20Liquid%2010g.png",
  "Lifebuoy Ice Bath 65g x 4": "/product-images/Lifebuoy%20Ice%20Bath%2065g%20x%204.png",
  "Lifebuoy Neem & Aloe Soap": "/product-images/Lifebuoy%20Neem%20and%20Aloe%20Soap.png",
  "Lifebuoy Total Protect": "/product-images/Lifebuoy%20Total%20Protect.png",
  "Lipton Clear And Light J&A 100g": "/product-images/Lipton%20Clear%20And%20Light%20J%20and%20A%20100g.png",
  "Lipton Green Tea Bags Honey Lemon 10 Pcs": "/product-images/Lipton%20Green%20Tea%20Bags%20Honey%20Lemon%2010%20Pcs.png",
  "Lipton Green Tea Clear & Light 10s TB": "/product-images/Lipton%20Green%20Tea%20Clear%20and%20Light%2010s%20TB.png",
  "Lipton Green Tea Honey Lemon 100g": "/product-images/Lipton%20Green%20Tea%20Honey%20Lemon%20100g.png",
  "Liril Bathing Soap Lime 75g": "/product-images/Liril%20Bathing%20Soap%20Lime%2075g.png",
  "Long Beans (Payeru)": "/product-images/Long%20Beans%20Payeru.png",
  "Lux Advanced Bright Glow": "/product-images/Lux%20Advanced%20Bright%20Glow.png",
  "Lux Bathing Soap Fresh Flash Water Lily & Cooling": "/product-images/Lux%20Bathing%20Soap%20Fresh%20Flash%20Water%20Lily%20and%20Cooling.png",
  "Lux Bathing Soap International Creamy Perfume": "/product-images/Lux%20Bathing%20Soap%20International%20Creamy%20Perfume.png",
  "Lux Bathing Soap Soft Touch 4 x 60g": "/product-images/Lux%20Bathing%20Soap%20Soft%20Touch%204%20x%2060g.png",
  "Lux Bathing Soap Velvet Touch Jasmine And Almond": "/product-images/Lux%20Bathing%20Soap%20Velvet%20Touch%20Jasmine%20And%20Almond.png",
  "Lux Glow Bar Collection": "/product-images/Lux%20Glow%20Bar%20Collection.png",
  "Lux Sandal Rs10 MLP": "/product-images/Lux%20Sandal%20Rs10%20MLP.png",
  "Maggi 2-Minute Noodles": "/product-images/Maggi%202-Minute%20Noodles.png",
  "Maggi Pazzta": "/product-images/Maggi%20Pazzta.png",
  "Maharaja Orid Dhall": "/product-images/Maharaja%20Orid%20Dhall.png",
  "Marie Gold": "/product-images/Marie%20Gold.png",
  "Maxo Coil (Mosquito Repellent)": "/product-images/Maxo%20Coil%20Mosquito%20Repellent.png",
  "Maxo Genius Combi": "/product-images/Maxo%20Genius%20Combi.png",
  "Meat Masala Powder": "/product-images/Meat%20Masala%20Powder.png",
  "Medimix Soap": "/product-images/Medimix%20Soap.png",
  "Milk Bikis Milk Cream": "/product-images/Milk%20Bikis%20Milk%20Cream.png",
  "Milk Rusk / Premium Bake Rusk": "/product-images/Milk%20Rusk%20Premium%20Bake%20Rusk.png",
  "Milk Rusk Restage": "/product-images/Milk%20Rusk%20Restage.png",
  "Milma Butter": "/product-images/Milma%20Butter.png",
  "Milma Ghee Cake": "/product-images/Milma%20Ghee%20Cake.png",
  "Milma Ghee Cake / Choco Brownie": "/product-images/Milma%20Ghee%20Cake%20Choco%20Brownie.png",
  "Milma Paneer": "/product-images/Milma%20Paneer.png",
  "Mint Leaves (Puthina)": "/product-images/Mint%20Leaves%20Puthina.png",
  "Munch Chocolate Wafer": "/product-images/Munch%20Chocolate%20Wafer.png",
  "Mutton Masala Powder": "/product-images/Mutton%20Masala%20Powder.png",
  "NC Cracker Lite": "/product-images/NC%20Cracker%20Lite.png",
  "NC Thin Arrowroot Biscuit": "/product-images/NC%20Thin%20Arrowroot%20Biscuit.png",
  "Nescafe Classic Jar": "/product-images/Nescafe%20Classic%20Jar.png",
  "Nescafe Sunrise": "/product-images/Nescafe%20Sunrise.png",
  "Nirmal Urutty Rose Rice": "/product-images/Nirmal%20Urutty%20Rose%20Rice.png",
  "Pavithram Gingelly (Sesame) Oil": "/product-images/Pavithram%20Gingelly%20Sesame%20Oil.png",
  "Pears Bathing Soap Oil Clear & Glow 75g": "/product-images/Pears%20Bathing%20Soap%20Oil%20Clear%20and%20Glow%2075g.png",
  "Pears Bathing Soap Pure & Gentle 60g": "/product-images/Pears%20Bathing%20Soap%20Pure%20and%20Gentle%2060g.png",
  "Pears Bathing Soap Soft & Fresh 100g": "/product-images/Pears%20Bathing%20Soap%20Soft%20and%20Fresh%20100g.png",
  "Pepsodent Toothpaste Germi Check Cavity Protection": "/product-images/Pepsodent%20Toothpaste%20Germi%20Check%20Cavity%20Protection.png",
  "Pond's Facewash Men Energy Charge 50g": "/product-images/Pond's%20Facewash%20Men%20Energy%20Charge%2050g.png",
  "Pond's Facewash Pure White Anti Pollution 50g": "/product-images/Pond's%20Facewash%20Pure%20White%20Anti%20Pollution%2050g.png",
  "Pond's Facewash White Beauty Spot Less Fairness": "/product-images/Pond's%20Facewash%20White%20Beauty%20Spot%20Less%20Fairness.png",
  "Pond's Pink Glow Face Talc 30g": "/product-images/Pond's%20Pink%20Glow%20Face%20Talc%2030g.png",
  "Pond's Talcum Powder Aloe 100g": "/product-images/Pond's%20Talcum%20Powder%20Aloe%20100g.png",
  "Pond's Talcum Powder Dreamflow 23g": "/product-images/Pond's%20Talcum%20Powder%20Dreamflow%2023g.png",
  "Pond's Talcum Powder Dreamflow Magic 20g": "/product-images/Pond's%20Talcum%20Powder%20Dreamflow%20Magic%2020g.png",
  "Ponds Aloe Cool 180g": "/product-images/Ponds%20Aloe%20Cool%20180g.png",
  "Potato": "/product-images/Potato.png",
  "Prakrithi Coconut Oil": "/product-images/Prakrithi%20Coconut%20Oil.png",
  "Pran Litchi Drink": "/product-images/Pran%20Litchi%20Drink.png",
  "Pran Pudding Jar": "/product-images/Pran%20Pudding%20Jar.png",
  "Premium Bake Rusk": "/product-images/Premium%20Bake%20Rusk.png",
  "Pringles Desi Masala": "/product-images/Pringles%20Desi%20Masala.png",
  "Pringles Original": "/product-images/Pringles%20Original.png",
  "Pringles Sour & Cream": "/product-images/Pringles%20Sour%20and%20Cream.png",
  "Pulari Rice Bran Oil": "/product-images/Pulari%20Rice%20Bran%20Oil.png",
  "QK Multigrain Oats": "/product-images/QK%20Multigrain%20Oats.png",
  "Quaker Oats": "/product-images/Quaker%20Oats.png",
  "R.G. Palm Oil": "/product-images/R.G.%20Palm%20Oil.png",
  "Raw Mango (Amrai)": "/product-images/Raw%20Mango%20Amrai.png",
  "Red Chilly Sauce": "/product-images/Red%20Chilly%20Sauce.png",
  "Red Label Tea Leaf Carton 250g": "/product-images/Red%20Label%20Tea%20Leaf%20Carton%20250g.png",
  "Red Label Tea Leaf Poly 100g": "/product-images/Red%20Label%20Tea%20Leaf%20Poly%20100g.png",
  "Red Label Tea Natural Care A Blend 250g": "/product-images/Red%20Label%20Tea%20Natural%20Care%20A%20Blend%20250g.png",
  "Red Masoor Dal": "/product-images/Red%20Masoor%20Dal.png",
  "Rexona Bathing Soap Coconut And Olive Oil": "/product-images/Rexona%20Bathing%20Soap%20Coconut%20And%20Olive%20Oil.png",
  "Rin Bleach Ala Bleach 200ml": "/product-images/Rin%20Bleach%20Ala%20Bleach%20200ml.png",
  "Rin Detergent Bar": "/product-images/Rin%20Detergent%20Bar.png",
  "Rin Detergent Powder 1kg": "/product-images/Rin%20Detergent%20Powder%201kg.png",
  "Rose Kaima Rice": "/product-images/Rose%20Kaima%20Rice.png",
  "Ruchi Gold Palm Oil": "/product-images/Ruchi%20Gold%20Palm%20Oil.png",
  "S S K Doppi Rice 1st": "/product-images/S%20S%20K%20Doppi%20Rice%201st.png",
  "Sambar Powder": "/product-images/Sambar%20Powder.png",
  "Santoor Soap (White/Set)": "/product-images/Santoor%20Soap%20White%20Set.png",
  "Sara Soap Podi (washing powder)": "/product-images/Sara%20Soap%20Podi%20washing%20powder.png",
  "Sarkara (Jaggery)": "/product-images/Sarkara%20Jaggery.png",
  "Sensodyne Fresh Gel Paste": "/product-images/Sensodyne%20Fresh%20Gel%20Paste.png",
  "Sensodyne Rapid Relief Paste": "/product-images/Sensodyne%20Rapid%20Relief%20Paste.png",
  "Sensodyne Sensitive Toothbrush": "/product-images/Sensodyne%20Sensitive%20Toothbrush.png",
  "Snickers": "/product-images/Snickers.png",
  "SSK Ponni Rice 1st": "/product-images/SSK%20Ponni%20Rice%201st.png",
  "Sunfeast Marie Glucose": "/product-images/Sunfeast%20Marie%20Glucose.png",
  "Sunfeast Marie Light": "/product-images/Sunfeast%20Marie%20Light.png",
  "Sunlight Detergent Powder": "/product-images/Sunlight%20Detergent%20Powder.png",
  "Sunlight Dishwash Liquid": "/product-images/Sunlight%20Dishwash%20Liquid.png",
  "Sunsilk Hair Conditioner Smooth & Tangle Free 80ml": "/product-images/Sunsilk%20Hair%20Conditioner%20Smooth%20and%20Tangle%20Free%2080ml.png",
  "Sunsilk Hair Shampoo Dream Soft & Smooth": "/product-images/Sunsilk%20Hair%20Shampoo%20Dream%20Soft%20and%20Smooth.png",
  "Sunsilk Hair Shampoo Lusciously Thick & Long": "/product-images/Sunsilk%20Hair%20Shampoo%20Lusciously%20Thick%20and%20Long.png",
  "Sunsilk Hair Shampoo Stunning Black Shine": "/product-images/Sunsilk%20Hair%20Shampoo%20Stunning%20Black%20Shine.png",
  "Sunsilk Thick & Long Twin (5.5+5.5)ml": "/product-images/Sunsilk%20Thick%20and%20Long%20Twin%205.5%20Plus%205.5ml.png",
  "Surf Excel Detergent Bar 100g": "/product-images/Surf%20Excel%20Detergent%20Bar%20100g.png",
  "Surf Excel Detergent Liquid Easy Wash 500ml": "/product-images/Surf%20Excel%20Detergent%20Liquid%20Easy%20Wash%20500ml.png",
  "Surf Excel Detergent Liquid Matic Front Load Refill": "/product-images/Surf%20Excel%20Detergent%20Liquid%20Matic%20Front%20Load%20Refill.png",
  "Surf Excel Detergent Liquid Matic Top Load Refill": "/product-images/Surf%20Excel%20Detergent%20Liquid%20Matic%20Top%20Load%20Refill.png",
  "Surf Excel Detergent Powder Easy Wash": "/product-images/Surf%20Excel%20Detergent%20Powder%20Easy%20Wash.png",
  "Surf Excel Detergent Powder Quick Wash 1kg": "/product-images/Surf%20Excel%20Detergent%20Powder%20Quick%20Wash%201kg.png",
  "Taaza Elaichi 250g": "/product-images/Taaza%20Elaichi%20250g.png",
  "Taaza Tea 100g": "/product-images/Taaza%20Tea%20100g.png",
  "Taaza Tea Masala Chaska Elaichi 250g": "/product-images/Taaza%20Tea%20Masala%20Chaska%20Elaichi%20250g.png",
  "Taj Mahal Tea Leaf 100g": "/product-images/Taj%20Mahal%20Tea%20Leaf%20100g.png",
  "Tiger Krunch Choco": "/product-images/Tiger%20Krunch%20Choco.png",
  "TRESemme Hair Conditioner Hair Fall Defense": "/product-images/TRESemme%20Hair%20Conditioner%20Hair%20Fall%20Defense.png",
  "TRESemme Hair Conditioner Keratin Smooth": "/product-images/TRESemme%20Hair%20Conditioner%20Keratin%20Smooth.png",
  "TRESemme Hair Conditioner Smooth & Shine": "/product-images/TRESemme%20Hair%20Conditioner%20Smooth%20and%20Shine.png",
  "TRESemme Hair Shampoo Hair Fall Defense 6ml": "/product-images/TRESemme%20Hair%20Shampoo%20Hair%20Fall%20Defense%206ml.png",
  "TRESemme Hair Shampoo Keratin Smooth 6ml": "/product-images/TRESemme%20Hair%20Shampoo%20Keratin%20Smooth%206ml.png",
  "TRESemme Smooth & Shine LCS 6ml": "/product-images/TRESemme%20Smooth%20and%20Shine%20LCS%206ml.png",
  "True Blue Dragon Noodles": "/product-images/True%20Blue%20Dragon%20Noodles.png",
  "TT Asafoetida (Kayam)": "/product-images/TT%20Asafoetida%20Kayam.png",
  "Turmeric Powder": "/product-images/Turmeric%20Powder.png",
  "Ujala Crystal White Liquid": "/product-images/Ujala%20Crystal%20White%20Liquid.png",
  "Ujala Y&F Bliss/Aura Sachet": "/product-images/Ujala%20Y%20and%20F%20Bliss%20Aura%20Sachet.png",
  "UT Appam Podi": "/product-images/UT%20Appam%20Podi.png",
  "UT Puttu Podi": "/product-images/UT%20Puttu%20Podi.png",
  "UT Uppuma Rava": "/product-images/UT%20Uppuma%20Rava.png",
  "V Wash Plus 100ml": "/product-images/V%20Wash%20Plus%20100ml.png",
  "Vim Bar 3x190g MPO": "/product-images/Vim%20Bar%203x190g%20MPO.png",
  "Vim Bar Tubs Anti-Smell 500g": "/product-images/Vim%20Bar%20Tubs%20Anti-Smell%20500g.png",
  "Vim Dishwash Bar 75g": "/product-images/Vim%20Dishwash%20Bar%2075g.png",
  "Vim Dishwash Bar Tub 500g": "/product-images/Vim%20Dishwash%20Bar%20Tub%20500g.png",
  "Vim Dishwash Gel Liquid Lemon 115ml": "/product-images/Vim%20Dishwash%20Gel%20Liquid%20Lemon%20115ml.png",
  "Vim Dishwash Gel Liquid Lemon 250ml": "/product-images/Vim%20Dishwash%20Gel%20Liquid%20Lemon%20250ml.png",
  "Vivel / Fiama products (assorted)": "/product-images/Vivel%20Fiama%20products%20assorted.png",
  "Wheel Detergent Powder Blue 1kg": "/product-images/Wheel%20Detergent%20Powder%20Blue%201kg.png",
  "Wheel L&O Powder A+ 4kg Blue": "/product-images/Wheel%20L%20and%20O%20Powder%20A%20Plus%204kg%20Blue.png",
  "Women's Horlicks Caramel Pet Jar 400g": "/product-images/Women's%20Horlicks%20Caramel%20Pet%20Jar%20400g.png",
  "Yardley English Rose Talc": "/product-images/Yardley%20English%20Rose%20Talc.png",
  "Yardley Lavender Talc": "/product-images/Yardley%20Lavender%20Talc.png",
  "Yardley Red Rose Talc": "/product-images/Yardley%20Red%20Rose%20Talc.png",
  "Yippee Magic Masala Noodles": "/product-images/Yippee%20Magic%20Masala%20Noodles.png",
};

export default productImages;
